services:
  web:
    build: .
    volumes:
      - .:/rails # Kodun tamamını bağla
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: redis://redis-db:6379/1
      # Veritabanı bilgilerini parçalı vermek Rails için daha sağlıklıdır
      DATABASE_HOST: postgres-db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgres-db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-db:
    image: redis